data:
  storageInitializer: |-
    {
      "image" : "kserve/storage-initializer:latest",
      "memoryRequest": "32Gi",
      "memoryLimit": "32Gi",
      "cpuRequest": "1",
      "cpuLimit": "1",
      "caBundleConfigMapName": "",
      "caBundleVolumeMountPath": "/etc/ssl/custom-certs",
      "enableDirectPvcVolumeMount": false,
      "enableModelcar": false,
      "cpuModelcar": "10m",
      "memoryModelcar": "15Mi"
    }