name: Move MLflow Artifacts to Blob
on:
  workflow_dispatch:

env:
  RUN_ID: da174a3779824c1fa7792e650df5b58a


jobs:
  main-job:
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Download mlflow artifacts
      env:
        DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
        DEST_PATH: "./artifacts"
      run: |
        export DATABRICKS_HOST=$DATABRICKS_HOST
        export DATABRICKS_TOKEN=$DATABRICKS_TOKEN
        export MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
        pip install mlflow
        echo DATABRICKS_HOST
        echo DATABRICKS_TOKEN
        echo MLFLOW_TRACKING_URI
        python download_mlflow_artifacts.py --run-id $RUN_ID --dest-path $DEST_PATH
