name: Python Package using Conda
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Install dependencies
      env:
        DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ vars.DATABRICKS_TOKEN }}
        MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}

      run: |
        export $DATABRICKS_HOST
        export $DATABRICKS_TOKEN
        export $MLFLOW_TRACKING_URI
        pip install mlflow
        python download_mlflow_artifacts.py
    
