name: Move MLflow Artifacts to Blob
on:
  workflow_dispatch:

env:
  RUN_ID: da174a3779824c1fa7792e650df5b58a


jobs:
  main-job:
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    
    # Not able to run due to IP allow list    
    # - name: Download mlflow artifacts
    #   env:
    #     DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
    #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    #     MLFLOW_TRACKING_URI: ${{ vars.MLFLOW_TRACKING_URI }}
    #     DEST_PATH: "./mlflow_artifacts"
    #   run: |
    #     export DATABRICKS_HOST=$DATABRICKS_HOST
    #     export DATABRICKS_TOKEN=$DATABRICKS_TOKEN
    #     export MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
    #     curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    #     databricks configure --token --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN
    #     pip install mlflow
    #     mlflow artifacts download --run-id $RUN_ID --dst-path $DEST_PATH

    - name: Conda pack
      run: |
        conda install conda-pack
        conda create -f artifacts/conda.yaml
        conda pack -n mlflow_env
