channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.3.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==2.0.0
  - langchain
  - langchain-community
  - llama-cpp-python
name: mlflow-env
variables:
  CMAKE_ARGS: -DLLAMA_CUBLAS=on
  FORCE_CMAKE: 1